id: D2D358C59
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:35:36+00:00'
last_modified: '2022-05-27T15:30:14.076654+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    '7664':
      image_group_id: I1PD95909
      title: བྱང་ཆུབ་སེམས་དཔའ་ལས་དང་པོ་པའི་ལམ་ལ་འཇུག་པ་བསྟན་པ།
      total_pages: 1902
      order: 64
      base_file: 7664.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
